name: build ssh

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  build-ssh:
    permissions: write-all
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: ssh to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
#          script: |
#            pwd
      - name: apply patch & build
        run: |
          cd /home/ubuntu/docker-compose && docker compose -f duo.yaml up -d --pull always
#          cd duo-website
#          echo ${{ env.VERSION }}
#          docker ps
